run:
  description: Runs a controller program or station
  fields:
    entity_id:
      description: Sensor or switch entity id for programs or stations
      example: "sensor.station_name"
    run_seconds:
      description: Number of seconds to run for (optional, stations only)
      example: 60
stop:
  description: Stops a controller station
  fields:
    entity_id:
      description: Sensor or switch entity id for stations
      example: "sensor.station_name"
